<?php

namespace CrCms\Microservice\Tests;

use CrCms\Microservice\Bootstrap\Start;
use CrCms\Microservice\Foundation\Application;

trait ApplicationTrait
{
    /**
     * @var Application
     */
    public static $app;

    public static function setUpBeforeClass()
    {
        // TODO: Change the autogenerated stub
        parent::setUpBeforeClass();
//        static::$app = new \CrCms\Microservice\Foundation\Application(__DIR__);

        static::$app = Start::instance()->bootstrap(__DIR__)->getApplication();

//        static::$app->bootstrapWith([
//            \Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables::class,
//            \CrCms\Microservice\Bootstrap\LoadConfiguration::class,
//            \CrCms\Microservice\Bootstrap\HandleExceptions::class,
//            \CrCms\Microservice\Bootstrap\RegisterFacades::class,
//            \Illuminate\Foundation\Bootstrap\SetRequestForConsole::class,
//            \Illuminate\Foundation\Bootstrap\RegisterProviders::class,
//            \Illuminate\Foundation\Bootstrap\BootProviders::class,
//        ]);

    }

    public static function tearDownAfterClass()
    {
        // TODO: Change the autogenerated stub
        parent::tearDownAfterClass();

        static::$app = null;
    }
}
