<?php

namespace CrCms\Microservice\Tests;

trait ApplicationTrait
{
    public static $app;

    public static function setUpBeforeClass()
    {
        // TODO: Change the autogenerated stub
        parent::setUpBeforeClass();
        static::$app = forkApp();
    }

    public static function tearDownAfterClass()
    {
        // TODO: Change the autogenerated stub
        parent::tearDownAfterClass();

        static::$app = null;
    }
}
